name: Export Resource Group Template

on:
  push:
    branches:
      - master  # or any other branch you prefer

jobs:
  export_template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Log in to Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Set Azure subscription
      run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Export Resource Group
      run: az group export --name Automation-new-env --skip-all-params --output json > template2.json

    - name: Upload to Azure Blob Storage
      run: az storage blob upload --account-name storagenewenvpsh1708  --container-name pdf-container --name template2.json --file template2.json --auth-mode key --account-key ${{ secrets.AZURE_STORAGE_KEY }}
